name: dashboard_widgets
description: A Flutter Dashboard Widget Package contains many customizable widgets that you can find in a typical dashboard .
version: 0.0.1
homepage: null
repository: https://github.com/asas-tech/dashboard_widgets
issue_tracker: https://github.com/asas-tech/pubbox/issues
documentation: https://asas-tech.github.io/pubbox/
environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  vrouter: ^1.2.0+11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

